import Head from 'next/head'

export default function AppHead() {
    return (
        <>
            <Head>
                <title>Ola Social APp</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/Logomark.png" />
            </Head>
        </>
    )
}